name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes (UTC)
  workflow_dispatch: # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render Service
        run: curl -s https://data-forge-50fl.onrender.com/health > /dev/null
